# Usa una imagen base con la versión de Java que necesitas
FROM sjcmag/spring:v1

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo JAR construido por Maven al contenedor
COPY /target/crudapp.jar app.jar

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 8080

# Comando para ejecutar la aplicación cuando se inicia el contenedor
CMD ["java", "-jar", "crudapp.jar"]
