# Usa una imagen base con la versión de Java que necesitas
FROM adoptopenjdk:11-jre-hotspot

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo JAR construido por Maven al contenedor
COPY target/your-project-name.jar app.jar

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 8080

# Comando para ejecutar la aplicación cuando se inicia el contenedor
CMD ["java", "-jar", "app.jar"]
